# MUST EDIT BELOW
sitename: the_minimum
tagline: themes for jekyll
url: http://your.site.com
# END
# CHOOSE YOUR PREFERENCE
pygments:    false
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown
