#Presentation Settings
sitename: the_minimum
tagline: themes for jekyll
url: http://your.site.com
#Deployment Settings
pygments:    false
markdown:    maruku
permalink:   pretty
exclude: LICENSE, README.markdown
